name: petsird-analytic-simulator
channels:
  - conda-forge
dependencies:
  - numpy>=1.24.3
  - python>=3.11.3
  - matplotlib>=3.8.0
  - parallelproj>=1.10.0
  - pymirc>=0.29
  - petsird~=0.7.2
  - ipython
