name: petsird-v0.2-parallelproj
channels:
  - conda-forge
  - defaults
dependencies:
  - h5py>=3.7.0
  - ipykernel>=6.19.2
  - numpy>=1.24.3
  - python>=3.11.3
  - matplotlib~=3.8.0
  - parallelproj>=1.10.0
  - pymirc>=0.29
  - pip
  - pip:
     - petsird==0.2 
